### ISSUE TITLE
Black's Method

### ISSUE THREAD

**Issue by cooljeanius** [tif-calin/votevote#9]
This is already listed in the TODO checklist in the README, but I'm hoping that opening an issue for it will lead to greater prioritization of it: basically, I'm kind of a fan of Black's Method, and would like to see it included: https://en.wikipedia.org/wiki/Black%27s_method

**Comment by tif-calin** [comment]
@cooljeanius Just added! Releasing today: https://github.com/tif-calin/votevote/pull/10

**Comment by tif-calin** [comment]
I'd love to hear more about why you're such a fan of Black's method. To be quite honest I found it kinda... boring? It doesn't even feel like a real voting method. Just a mashing of two existing voting methods (sorta) together.

**Comment by cooljeanius** [comment]
> I'd love to hear more about why you're such a fan of Black's method. To be quite honest I found it kinda... boring? It doesn't even feel like a real voting method. Just a mashing of two existing voting methods (sorta) together.

Basically, just because it meets a large number of criteria for what we might consider a "good" method: it satisfies Anonymity, Neutrality, Unanimity, Majority, Condorcet, Anti-Condorcet, Monotonicity, and Pareto, for a total of 8. (Of course, Copeland's Method also satisfies all 8 of these criteria, but I believe that you already had that one.)

Ref.: 
Robinson Jr., E. Arthur; Ullman, Daniel H. (2011). ***A Mathematical Look at Politics.*** Boca Raton, FL: CRC Press, an imprint of Taylor and Francis Group, LLC. p. 74. [ISBN](https://en.wikipedia.org/wiki/ISBN_(identifier)) [978-1-4398-1983-8](https://en.wikipedia.org/wiki/Special:BookSources/978-1-4398-1983-8).

**Comment by tif-calin** [comment]
Haha yeah. I feel like most voting theory nerds that judge by number of mathematical criteria met would say something like River or Ranked Pairs. I don't know that many fellow nerds but I you're the first I've met that likes Black the most

Anyways thanks for opening the issue and chatting. Since Black's is now implemented I'm gonna go ahead and close it
